version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isgi_docs_app
    ports:
        - "8080:9000"
        - "8000:8000"
    volumes:
      - .:/var/www/html # Montez le projet local dans le conteneur
    environment:
      APP_ENV: local
      APP_KEY: base64:your_app_key_here
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: docs-isgi-db
      DB_USERNAME: root
      DB_PASSWORD: SAAZwinners9305@
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: isgi_docs_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SAAZwinners9305@
      MYSQL_DATABASE: docs-isgi-db
      MYSQL_PASSWORD: SAAZwinners9305@
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
